### PR TITLE
feat: turn into a progressive web app

### PR DESCRIPTION
**Pull request by YonatanKra**
How to make it work:
1. yarn nx build --prod
2. npm i -g http-server
3. http-server -p 8080 -c-1 dist/apps/vaccitron
4. Go to http://localhost:8080
The app should load.
You should see the following:
1. It should offer to install the app (on desktop it should appear in the URL line)
2. It should load the app even if there's no internet connection (via the service worker)

### CODE REVIEW

**Review by idigra — COMMENTED** [review]
I wanted to test the branch locally, is there a functional change that can be tested?
(If so, consider documenting how to test it in a Readm.md).

**Comment by YonatanKra** [comment]
> I wanted to test the branch locally, is there a functional change that can be tested?
> (If so, consider documenting how to test it in a Readm.md).

@MaMazav @idigra 
Updated the PR's description

**Comment by idigra** [comment]
> > I wanted to test the branch locally, is there a functional change that can be tested?
> > (If so, consider documenting how to test it in a Readm.md).
> 
> @MaMazav @idigra
> Updated the PR's description

1. It's complex enough to be in Readme.md in the codebase.
2. The address in 4 is not accurate: Notice that when you use http-server, it's not https but http.
3. How can I trigger an push alert to test?

**Comment by YonatanKra** [comment]
> > > I wanted to test the branch locally, is there a functional change that can be tested?
> > > (If so, consider documenting how to test it in a Readm.md).
> > 
> > 
> > @MaMazav @idigra
> > Updated the PR's description
> 
> 1. It's complex enough to be in Readme.md in the code.
> 2. The address in 4 is not accurate: Notice that when you use http-server, it's not https but http.
> 3. How can I trigger an push alert to test?

1. I don't think it is. This is basic PWA stuff... 
2. Correct - updated the thingy
3. You cannot. Push notifications are a whole different story. This is just the basic client-side infra to allow the possibility of push notifications. When I'll add push notifications, you'll have a `spec` file that will test them...

**Review by idigra — APPROVED** [review]
Approving to unblock although not agreed :)
We might want to talk more about such stuff in the future if having time.

**Pull request merged**
